baseURL = 'https://yelobat.github.io/'
languageCode = 'en-us'
title = 'yelobat - Homepage'
theme = 'nostyleplease'

[markup.goldmark.renderer]
    unsafe = true

[caches]
    [caches.images]
        dir = ':cacheDir/images'

